#!/bin/bash

# In order to ensure that we get a good, self-consistent backup, we put the
# Minecraft server into read-only mode while we copy the data files.  Players
# can continue to craft, and their changes will automatically be saved as soon
# as we finish the backup and exit read-only mode.  In other words, this should
# be totally transparent, but we might as well broadcast a message to anyone
# who's currently connected, so that they aren't confused and alarmed by the
# messages telling them that their world is no longer being saved.
# WHERE'S YOUR GOD NOW?


SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR"/config
TELL_MINECRAFT=$SCRIPT_DIR/tell_minecraft

$TELL_MINECRAFT "say It's backup time!"
$TELL_MINECRAFT 'save-off'
$TELL_MINECRAFT 'save-all'
sleep 10  # HACK: Wait until (we think) save-all is complete.
zip -r "$MINECRAFT_BACKUP_DIR"/minecraft-backup-`date +\%F`.zip \
       $MINECRAFT_DATA_DIR
$TELL_MINECRAFT 'save-on'
$TELL_MINECRAFT 'say Backup complete!'
