#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR"/config

STARTUP_WAIT_SECS=30
MINECRAFT_JAR=$( \
	ls -t "$MINECRAFT_SERVER_DIR"/minecraft_server.*.jar \
        | head -1 )
JAVA_FLAGS='-Xmx3072M -Xms3072M'

QUIET=
[[ $1 == -q ]] && QUIET=1

if screen -ls | grep -q minecraft; then
    if [[ -z $QUIET ]]; then
        >&2 echo 'Minecraft screen session is already started!'
        exit 1
    else
        exit 0
    fi
fi

cd `dirname $MINECRAFT_JAR`
screen -d -m -c /dev/null -S minecraft \
   java $JAVA_FLAGS -jar `basename $MINECRAFT_JAR` nogui
#sleep $STARTUP_WAIT_SECS  # Wait for the server to finish starting up.
#tell_minecraft 'gamerule mobGriefing false'
echo Starting Minecraft server in a screen session!
echo Using $MINECRAFT_JAR
